### PR TITLE
Support node 0.12

### PR DESCRIPTION
**Pull request by TrySound**
Hi, Lee! Nice to meet you. Rollup still supports 0.12 until december. I'd like to use your plugin in my prodution.

### CODE REVIEW

**Comment by leebyron** [comment]
Thanks!

**Comment by TrySound** [comment]
Could this be released too?

**Comment by leebyron** [comment]
https://github.com/leebyron/rollup-plugin-flow/releases/tag/v1.0.1

**Comment by TrySound** [comment]
Thanks, Lee!

**Pull request merged**
